### PR TITLE
Refactor back end images view (search tools)

### PR DESCRIPTION
**Pull request by Erftralle**
This pull request introduces the new Joomla! search tools in the back end images view.

The search tools replace the filter boxes in the sidebar and make ordering easier.  Another nice side effect is, that the AJAX category selection is now available as filter as well as the owner filter selection box in the case that the system has a lot of users.

To avoid new language constants I created a new list box field (Joomlist) derived from the standard Joomla! list box which is just able to combine multiple language constants for a select option (see file filter_images.xml).

Hope you will enjoy it and for that case we could introduce the search tools also in other JoomGallery managers.

### CODE REVIEW

**Comment by Chraneco** [comment]
That's awesome! Thank you very much, I would l would be in favor of making the same changes to the other managers as well.

There is only one thing I would change: Right now the user selection is always done through the popup. For websites with only a few users I would keep using the dropdown box like the content manager of Joomla is using it, too. This way it is much faster and more convenient for administrators to use the filter and it also looks consistent with the content manager. The one with the popup should be used only if is a large amount of users.

It also looks like the JHtml 'select.usersPopup' is not used anywhere anymore. If you can confirm that we could delete this method.

**Comment by Erftralle** [comment]
Thanks for your feedback.

I followed your proposal to use a dropdown box for owner selection up to 250 (same maximum user count than in ```JHtmlJoomSelect::users()```) users. Maybe it would be worth to create a configuration option for the maximum user count (later for JoomGallery 3.3) ?

I removed the code ```JHtmlJoomSelect::usersPopup()```.

**Comment by Chraneco** [comment]
Great, thanks!
To not forget about that option I added a note for it in #56.

**Comment by MrMusic** [comment]
Works great! :thumbsup:  Many thanks.
Especially since now the ajax Category selection works fine. :smile:

**Comment by Erftralle** [comment]
Thanks @MrMusic for testing and your feedback :smile: .
Maybe you would like to test #60 ?

**Pull request merged**
