### PR TITLE
Quick editing of image data in Userpanel

### PR DESCRIPTION
**Pull request by VitUrzh**
If user want to quickly make a lot of corrections in a images data
Screenshot:
http://www.awesomescreenshot.com/image/93094/5a3d5381af1bf6408d13604c49299c6a

### CODE REVIEW

**Comment by Chraneco** [comment]
Thanks for this big contribution!

Finally, I had some time to have a look at this. I really like the idea, this should definitely become part of JoomGallery.

While reviewing the code I detected a few things that I wanted to change:
- Making the new code consistent with the rest of JoomGallery
- Trying to reduce the amount of additional CSS
- Removing the need for distinguishing between the different editors
- Using the JSON document type for responding to the Ajax request
- Validating and filtering the data through JForm
- Authorization check

I created a pull request with these changes to your repository: https://github.com/VitUrzh/JoomGallery/pull/2

If you merge this request you can test the changes and the pull request to the original JoomGallery repository should be automatically updated so that we can merge everything back into the v3.3.0 branch.

**Comment by JoshuaLewis** [comment]
This is really awesome! I'm quite pleased to see a serious effort made for easier management of images in Joomgallery. One of the best UX fixes I can think of in terms of making managing the gallery easier for users.

**Comment by Erftralle** [comment]
Would really like to have a look at the result of @VitUrzh and @Chraneco combined work.

**Comment by Chraneco** [comment]
The combined work can be found in this branch of the forked repository: https://github.com/Chraneco/JoomGallery/tree/userpanel
Would be great if you could test it!

**Comment by Erftralle** [comment]
Thanks to @VitUrzh and @Chraneco for this awesome work, I like it! :+1:

During my tests I found some minor issues:

- Sorting (by Date, Ordering ...) in the user panel is broken
- After saving there is a message ```undefined``` in the sytem message container
- If just changing the format of the text in an image description (e.g. formatting a word to bold) a field change is not recognized and a save is not possible
- The image title field is not marked as required (like declared in the XML file) and when saving an empty image title there is no client side validation, the AJAX response message shown in the popup is not very user friendly ;-)
- When clicking on the icon to display the quick editing units it would be nice to have the unit focused that has been clicked on
- The class document block in the file userpanel.json.php has not been adapted (JSON Vote Controller ;-))
- I don't understand the check in lines 427-431 of the file edit.php
- Missing file documentation block in userpanel.js
- it would be very nice to have a JoomGallery configuration option to enable/disable the quick editing

**Comment by Chraneco** [comment]
Thanks for the extensive testing! I updated my branch with corresponding changes.

> Sorting (by Date, Ordering ...) in the user panel is broken

Works again now. Unfortunately, it doesn't seem to be possible right now to use custom form names when using the table ordering functionality of Joomla's JavaScript. The form is named 'adminForm' again now.

> After saving there is a message undefined in the sytem message container

The language constant is corrected now.

> If just changing the format of the text in an image description (e.g. formatting a word to bold) a field change is not recognized and a save is not possible

Unfortunately, I didn't find an easy way to fix this. The editors don't provide an event for changes and triggering the enabling of the save button based on a click in that area would also enable the save when someone just clicks on the text area. Maybe someone else has an idea for that. For now it's necessary to quickly change a character and revert it back in this case in order to enable the save action.

> The image title field is not marked as required (like declared in the XML file) and when saving an empty image title there is no client side validation, the AJAX response message shown in the popup is not very user friendly ;-)

This is fixed now.

> When clicking on the icon to display the quick editing units it would be nice to have the unit focused that has been clicked on

Right, now the corresponding image title field is focused and the page scrolls up to the respective editing unit.

> The class document block in the file userpanel.json.php has not been adapted (JSON Vote Controller ;-))

Fixed ;)

> I don't understand the check in lines 427-431 of the file edit.php

The line first converts the input to an integer and then checks whether it is 0. I made two lines out of that now in order to make it more explicit.

> Missing file documentation block in userpanel.js

Added :)

> it would be very nice to have a JoomGallery configuration option to enable/disable the quick editing 

Since this is only a little button appearing in addition to others and since this is only in the member area, I think adding an option for this is not necessary, it feels like an overload ;).

**Comment by Erftralle** [comment]
For me everything is fine now. Thank you!

> Unfortunately, I didn't find an easy way to fix this. The editors don't provide an event for changes and triggering the enabling of the save button based on a click in that area would also enable the save when someone just clicks on the text area. Maybe someone else has an idea for that. For now it's necessary to quickly change a character and revert it back in this case in order to enable the save action.

I don't have a solution for it either. I can live with that. 

> Since this is only a little button appearing in addition to others and since this is only in the member area, I think adding an option for this is not necessary, it feels like an overload ;).

To provide an option for that would not be so much work and would give the user the possibility to decide themselves. It would be also more backward compatible because one could set the option to not allow quick editing by default. An update to the new JoomGallery version then would not lead to a surprise. I personally would not want to allow the users of my site to change the meta data of each image just because most of them even don't know what this is ;-).

**Comment by Chraneco** [comment]
You are right, I did not think about the fact that is was not possible to edit the metadata in the frontend. I updated my branch with a new option for that and consequently added the respective fields also in the edit and editcategory views.

Now it should not be a problem anymore to have this little icon in the userpanel by default. I don't treat this as an optional additional feature, but more as an enhancement of the user experience.

**Comment by Erftralle** [comment]
Good solution :100: , thank you. Successfully tested.

**Comment by Chraneco** [comment]
Awesome, thanks for testing!
I merged this pull request and redirected my pull request with the additions to the original JoomGallery repository. This way VitUrzh's contributions stay instact in the history in order to give him credit.

**Comment by JoshuaLewis** [comment]
So will this feature be included in Joomgallery 3.3?

**Comment by Chraneco** [comment]
Yes, now that it's merged it will be included in the 3.3 release.

**Comment by JoshuaLewis** [comment]
Yeay! :-D Thanks everyone for your contributions.

**Comment by MrMusic** [comment]
I tested the actual 3.3.0 branch with the quick edit. Two things I did notice:
1. It is only possible to change the meta description. Meta keywords is missing in the Quick Edit, or is intentional?
2. if i makes an update of an existing JoomGallery, the file media/joomgallery/js/userpanel.js is missing. Probably because it is deleted in the script.php, line 284?

But definitely a cool feature. :+1:

**Comment by Chraneco** [comment]
Thanks for testing!

I think the missing keywords field is intentional. The quick edit is supposed to contain only the most important fields. I guess @VitUrzh selected only the description field because this one is more likely to be updated. I can't say anything about that because personally, I don't use these settings yet, but I am open for other opinions. Maybe we should put it in as well.

In terms of the userpanel.js file: This one does not exist anymore. You shouldn't get it in a new installation, either.

**Comment by Erftralle** [comment]
> In terms of the userpanel.js file: This one does not exist anymore. You shouldn't get it in a new installation, either.

Are you sure ? The file userpanel.js contains the Javascript for this new feature and must not be deleted in case of an update.

**Comment by Chraneco** [comment]
Sorry, you are right. I only looked in the master branch for that file.
With the latest commit this should be fixed. Thanks to the both of you!

**Pull request merged**
